//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PresentacionMovil.asmxPedido {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PedidoAsmxSoap", Namespace="http://tempuri.org/")]
    public partial class PedidoAsmx : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NuevoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevolverPedidoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevolverListaPedidosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarPedidoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevolverListaPedidosPorClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PedidoAsmx() {
            this.Url = "http://proyectopedidos.somee.com/PedidoAsmx.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NuevoCompletedEventHandler NuevoCompleted;
        
        /// <remarks/>
        public event ActualizarCompletedEventHandler ActualizarCompleted;
        
        /// <remarks/>
        public event DevolverPedidoPorIdCompletedEventHandler DevolverPedidoPorIdCompleted;
        
        /// <remarks/>
        public event DevolverListaPedidosCompletedEventHandler DevolverListaPedidosCompleted;
        
        /// <remarks/>
        public event EliminarPedidoPorIdCompletedEventHandler EliminarPedidoPorIdCompleted;
        
        /// <remarks/>
        public event DevolverListaPedidosPorClienteCompletedEventHandler DevolverListaPedidosPorClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Nuevo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoEntidades Nuevo(PedidoEntidades pedido) {
            object[] results = this.Invoke("Nuevo", new object[] {
                        pedido});
            return ((PedidoEntidades)(results[0]));
        }
        
        /// <remarks/>
        public void NuevoAsync(PedidoEntidades pedido) {
            this.NuevoAsync(pedido, null);
        }
        
        /// <remarks/>
        public void NuevoAsync(PedidoEntidades pedido, object userState) {
            if ((this.NuevoOperationCompleted == null)) {
                this.NuevoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNuevoOperationCompleted);
            }
            this.InvokeAsync("Nuevo", new object[] {
                        pedido}, this.NuevoOperationCompleted, userState);
        }
        
        private void OnNuevoOperationCompleted(object arg) {
            if ((this.NuevoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NuevoCompleted(this, new NuevoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Actualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoEntidades Actualizar(PedidoEntidades pedido) {
            object[] results = this.Invoke("Actualizar", new object[] {
                        pedido});
            return ((PedidoEntidades)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarAsync(PedidoEntidades pedido) {
            this.ActualizarAsync(pedido, null);
        }
        
        /// <remarks/>
        public void ActualizarAsync(PedidoEntidades pedido, object userState) {
            if ((this.ActualizarOperationCompleted == null)) {
                this.ActualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarOperationCompleted);
            }
            this.InvokeAsync("Actualizar", new object[] {
                        pedido}, this.ActualizarOperationCompleted, userState);
        }
        
        private void OnActualizarOperationCompleted(object arg) {
            if ((this.ActualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCompleted(this, new ActualizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolverPedidoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoEntidades DevolverPedidoPorId(int identificador) {
            object[] results = this.Invoke("DevolverPedidoPorId", new object[] {
                        identificador});
            return ((PedidoEntidades)(results[0]));
        }
        
        /// <remarks/>
        public void DevolverPedidoPorIdAsync(int identificador) {
            this.DevolverPedidoPorIdAsync(identificador, null);
        }
        
        /// <remarks/>
        public void DevolverPedidoPorIdAsync(int identificador, object userState) {
            if ((this.DevolverPedidoPorIdOperationCompleted == null)) {
                this.DevolverPedidoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevolverPedidoPorIdOperationCompleted);
            }
            this.InvokeAsync("DevolverPedidoPorId", new object[] {
                        identificador}, this.DevolverPedidoPorIdOperationCompleted, userState);
        }
        
        private void OnDevolverPedidoPorIdOperationCompleted(object arg) {
            if ((this.DevolverPedidoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevolverPedidoPorIdCompleted(this, new DevolverPedidoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolverListaPedidos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoEntidades[] DevolverListaPedidos() {
            object[] results = this.Invoke("DevolverListaPedidos", new object[0]);
            return ((PedidoEntidades[])(results[0]));
        }
        
        /// <remarks/>
        public void DevolverListaPedidosAsync() {
            this.DevolverListaPedidosAsync(null);
        }
        
        /// <remarks/>
        public void DevolverListaPedidosAsync(object userState) {
            if ((this.DevolverListaPedidosOperationCompleted == null)) {
                this.DevolverListaPedidosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevolverListaPedidosOperationCompleted);
            }
            this.InvokeAsync("DevolverListaPedidos", new object[0], this.DevolverListaPedidosOperationCompleted, userState);
        }
        
        private void OnDevolverListaPedidosOperationCompleted(object arg) {
            if ((this.DevolverListaPedidosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevolverListaPedidosCompleted(this, new DevolverListaPedidosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarPedidoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarPedidoPorId(int identificador) {
            object[] results = this.Invoke("EliminarPedidoPorId", new object[] {
                        identificador});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarPedidoPorIdAsync(int identificador) {
            this.EliminarPedidoPorIdAsync(identificador, null);
        }
        
        /// <remarks/>
        public void EliminarPedidoPorIdAsync(int identificador, object userState) {
            if ((this.EliminarPedidoPorIdOperationCompleted == null)) {
                this.EliminarPedidoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarPedidoPorIdOperationCompleted);
            }
            this.InvokeAsync("EliminarPedidoPorId", new object[] {
                        identificador}, this.EliminarPedidoPorIdOperationCompleted, userState);
        }
        
        private void OnEliminarPedidoPorIdOperationCompleted(object arg) {
            if ((this.EliminarPedidoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarPedidoPorIdCompleted(this, new EliminarPedidoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolverListaPedidosPorCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoEntidades[] DevolverListaPedidosPorCliente(int idCliente) {
            object[] results = this.Invoke("DevolverListaPedidosPorCliente", new object[] {
                        idCliente});
            return ((PedidoEntidades[])(results[0]));
        }
        
        /// <remarks/>
        public void DevolverListaPedidosPorClienteAsync(int idCliente) {
            this.DevolverListaPedidosPorClienteAsync(idCliente, null);
        }
        
        /// <remarks/>
        public void DevolverListaPedidosPorClienteAsync(int idCliente, object userState) {
            if ((this.DevolverListaPedidosPorClienteOperationCompleted == null)) {
                this.DevolverListaPedidosPorClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevolverListaPedidosPorClienteOperationCompleted);
            }
            this.InvokeAsync("DevolverListaPedidosPorCliente", new object[] {
                        idCliente}, this.DevolverListaPedidosPorClienteOperationCompleted, userState);
        }
        
        private void OnDevolverListaPedidosPorClienteOperationCompleted(object arg) {
            if ((this.DevolverListaPedidosPorClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevolverListaPedidosPorClienteCompleted(this, new DevolverListaPedidosPorClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PedidoEntidades {
        
        private int idField;
        
        private int idClienteField;
        
        private int idRepartidorField;
        
        private System.DateTime fechaCreacionField;
        
        private string estadoField;
        
        private double totalField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public int IdRepartidor {
            get {
                return this.idRepartidorField;
            }
            set {
                this.idRepartidorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void NuevoCompletedEventHandler(object sender, NuevoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NuevoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NuevoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoEntidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoEntidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ActualizarCompletedEventHandler(object sender, ActualizarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoEntidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoEntidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DevolverPedidoPorIdCompletedEventHandler(object sender, DevolverPedidoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevolverPedidoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevolverPedidoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoEntidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoEntidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DevolverListaPedidosCompletedEventHandler(object sender, DevolverListaPedidosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevolverListaPedidosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevolverListaPedidosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoEntidades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoEntidades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EliminarPedidoPorIdCompletedEventHandler(object sender, EliminarPedidoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarPedidoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarPedidoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DevolverListaPedidosPorClienteCompletedEventHandler(object sender, DevolverListaPedidosPorClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevolverListaPedidosPorClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevolverListaPedidosPorClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoEntidades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoEntidades[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591