//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PresentacionMovil.wcfDetallePedido {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDetallePedido", Namespace="http://tempuri.org/")]
    public partial class DetallePedido : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NuevoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDetallePedidoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevolerListaDetallesPorPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDetallesPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DetallePedido() {
            this.Url = "http://proyectopedidos.somee.com/DetallePedido.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NuevoCompletedEventHandler NuevoCompleted;
        
        /// <remarks/>
        public event EliminarDetallePedidoPorIdCompletedEventHandler EliminarDetallePedidoPorIdCompleted;
        
        /// <remarks/>
        public event DevolerListaDetallesPorPedidoCompletedEventHandler DevolerListaDetallesPorPedidoCompleted;
        
        /// <remarks/>
        public event EliminarDetallesPorIdCompletedEventHandler EliminarDetallesPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDetallePedido/Nuevo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DetallePedidoEntidades Nuevo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DetallePedidoEntidades detallePedido) {
            object[] results = this.Invoke("Nuevo", new object[] {
                        detallePedido});
            return ((DetallePedidoEntidades)(results[0]));
        }
        
        /// <remarks/>
        public void NuevoAsync(DetallePedidoEntidades detallePedido) {
            this.NuevoAsync(detallePedido, null);
        }
        
        /// <remarks/>
        public void NuevoAsync(DetallePedidoEntidades detallePedido, object userState) {
            if ((this.NuevoOperationCompleted == null)) {
                this.NuevoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNuevoOperationCompleted);
            }
            this.InvokeAsync("Nuevo", new object[] {
                        detallePedido}, this.NuevoOperationCompleted, userState);
        }
        
        private void OnNuevoOperationCompleted(object arg) {
            if ((this.NuevoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NuevoCompleted(this, new NuevoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDetallePedido/EliminarDetallePedidoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarDetallePedidoPorId(int identificador, [System.Xml.Serialization.XmlIgnoreAttribute()] bool identificadorSpecified, out bool EliminarDetallePedidoPorIdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EliminarDetallePedidoPorIdResultSpecified) {
            object[] results = this.Invoke("EliminarDetallePedidoPorId", new object[] {
                        identificador,
                        identificadorSpecified});
            EliminarDetallePedidoPorIdResult = ((bool)(results[0]));
            EliminarDetallePedidoPorIdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EliminarDetallePedidoPorIdAsync(int identificador, bool identificadorSpecified) {
            this.EliminarDetallePedidoPorIdAsync(identificador, identificadorSpecified, null);
        }
        
        /// <remarks/>
        public void EliminarDetallePedidoPorIdAsync(int identificador, bool identificadorSpecified, object userState) {
            if ((this.EliminarDetallePedidoPorIdOperationCompleted == null)) {
                this.EliminarDetallePedidoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDetallePedidoPorIdOperationCompleted);
            }
            this.InvokeAsync("EliminarDetallePedidoPorId", new object[] {
                        identificador,
                        identificadorSpecified}, this.EliminarDetallePedidoPorIdOperationCompleted, userState);
        }
        
        private void OnEliminarDetallePedidoPorIdOperationCompleted(object arg) {
            if ((this.EliminarDetallePedidoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDetallePedidoPorIdCompleted(this, new EliminarDetallePedidoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDetallePedido/DevolerListaDetallesPorPedido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
        public DetallePedidoEntidades[] DevolerListaDetallesPorPedido(int idPedido, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idPedidoSpecified) {
            object[] results = this.Invoke("DevolerListaDetallesPorPedido", new object[] {
                        idPedido,
                        idPedidoSpecified});
            return ((DetallePedidoEntidades[])(results[0]));
        }
        
        /// <remarks/>
        public void DevolerListaDetallesPorPedidoAsync(int idPedido, bool idPedidoSpecified) {
            this.DevolerListaDetallesPorPedidoAsync(idPedido, idPedidoSpecified, null);
        }
        
        /// <remarks/>
        public void DevolerListaDetallesPorPedidoAsync(int idPedido, bool idPedidoSpecified, object userState) {
            if ((this.DevolerListaDetallesPorPedidoOperationCompleted == null)) {
                this.DevolerListaDetallesPorPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevolerListaDetallesPorPedidoOperationCompleted);
            }
            this.InvokeAsync("DevolerListaDetallesPorPedido", new object[] {
                        idPedido,
                        idPedidoSpecified}, this.DevolerListaDetallesPorPedidoOperationCompleted, userState);
        }
        
        private void OnDevolerListaDetallesPorPedidoOperationCompleted(object arg) {
            if ((this.DevolerListaDetallesPorPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevolerListaDetallesPorPedidoCompleted(this, new DevolerListaDetallesPorPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDetallePedido/EliminarDetallesPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarDetallesPorId(int identificador, [System.Xml.Serialization.XmlIgnoreAttribute()] bool identificadorSpecified, out bool EliminarDetallesPorIdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EliminarDetallesPorIdResultSpecified) {
            object[] results = this.Invoke("EliminarDetallesPorId", new object[] {
                        identificador,
                        identificadorSpecified});
            EliminarDetallesPorIdResult = ((bool)(results[0]));
            EliminarDetallesPorIdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EliminarDetallesPorIdAsync(int identificador, bool identificadorSpecified) {
            this.EliminarDetallesPorIdAsync(identificador, identificadorSpecified, null);
        }
        
        /// <remarks/>
        public void EliminarDetallesPorIdAsync(int identificador, bool identificadorSpecified, object userState) {
            if ((this.EliminarDetallesPorIdOperationCompleted == null)) {
                this.EliminarDetallesPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDetallesPorIdOperationCompleted);
            }
            this.InvokeAsync("EliminarDetallesPorId", new object[] {
                        identificador,
                        identificadorSpecified}, this.EliminarDetallesPorIdOperationCompleted, userState);
        }
        
        private void OnEliminarDetallesPorIdOperationCompleted(object arg) {
            if ((this.EliminarDetallesPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDetallesPorIdCompleted(this, new EliminarDetallesPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class DetallePedidoEntidades {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int conseguidoField;
        
        private bool conseguidoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int idPedidoPerteneceField;
        
        private bool idPedidoPerteneceFieldSpecified;
        
        private int idProductoTiendaField;
        
        private bool idProductoTiendaFieldSpecified;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        /// <remarks/>
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Conseguido {
            get {
                return this.conseguidoField;
            }
            set {
                this.conseguidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConseguidoSpecified {
            get {
                return this.conseguidoFieldSpecified;
            }
            set {
                this.conseguidoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdPedidoPertenece {
            get {
                return this.idPedidoPerteneceField;
            }
            set {
                this.idPedidoPerteneceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPedidoPerteneceSpecified {
            get {
                return this.idPedidoPerteneceFieldSpecified;
            }
            set {
                this.idPedidoPerteneceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdProductoTienda {
            get {
                return this.idProductoTiendaField;
            }
            set {
                this.idProductoTiendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdProductoTiendaSpecified {
            get {
                return this.idProductoTiendaFieldSpecified;
            }
            set {
                this.idProductoTiendaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void NuevoCompletedEventHandler(object sender, NuevoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NuevoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NuevoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DetallePedidoEntidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetallePedidoEntidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EliminarDetallePedidoPorIdCompletedEventHandler(object sender, EliminarDetallePedidoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarDetallePedidoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarDetallePedidoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EliminarDetallePedidoPorIdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EliminarDetallePedidoPorIdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DevolerListaDetallesPorPedidoCompletedEventHandler(object sender, DevolerListaDetallesPorPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevolerListaDetallesPorPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevolerListaDetallesPorPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DetallePedidoEntidades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetallePedidoEntidades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EliminarDetallesPorIdCompletedEventHandler(object sender, EliminarDetallesPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarDetallesPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarDetallesPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EliminarDetallesPorIdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EliminarDetallesPorIdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591