//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PresentacionMovil.asmxUsuario {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsuarioAsmxSoap", Namespace="http://tempuri.org/")]
    public partial class UsuarioAsmx : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NuevoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevolverUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsuarioAsmx() {
            this.Url = "http://proyectopedidos.somee.com/UsuarioAsmx.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NuevoCompletedEventHandler NuevoCompleted;
        
        /// <remarks/>
        public event DevolverUsuarioCompletedEventHandler DevolverUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Nuevo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioEntidades Nuevo(UsuarioEntidades usuario) {
            object[] results = this.Invoke("Nuevo", new object[] {
                        usuario});
            return ((UsuarioEntidades)(results[0]));
        }
        
        /// <remarks/>
        public void NuevoAsync(UsuarioEntidades usuario) {
            this.NuevoAsync(usuario, null);
        }
        
        /// <remarks/>
        public void NuevoAsync(UsuarioEntidades usuario, object userState) {
            if ((this.NuevoOperationCompleted == null)) {
                this.NuevoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNuevoOperationCompleted);
            }
            this.InvokeAsync("Nuevo", new object[] {
                        usuario}, this.NuevoOperationCompleted, userState);
        }
        
        private void OnNuevoOperationCompleted(object arg) {
            if ((this.NuevoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NuevoCompleted(this, new NuevoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolverUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioEntidades DevolverUsuario(string username) {
            object[] results = this.Invoke("DevolverUsuario", new object[] {
                        username});
            return ((UsuarioEntidades)(results[0]));
        }
        
        /// <remarks/>
        public void DevolverUsuarioAsync(string username) {
            this.DevolverUsuarioAsync(username, null);
        }
        
        /// <remarks/>
        public void DevolverUsuarioAsync(string username, object userState) {
            if ((this.DevolverUsuarioOperationCompleted == null)) {
                this.DevolverUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevolverUsuarioOperationCompleted);
            }
            this.InvokeAsync("DevolverUsuario", new object[] {
                        username}, this.DevolverUsuarioOperationCompleted, userState);
        }
        
        private void OnDevolverUsuarioOperationCompleted(object arg) {
            if ((this.DevolverUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevolverUsuarioCompleted(this, new DevolverUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioEntidades {
        
        private int idField;
        
        private int idTipoUsuarioField;
        
        private string nombreField;
        
        private string userField;
        
        private string contraseñaField;
        
        private System.DateTime fechaCreacionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoUsuario {
            get {
                return this.idTipoUsuarioField;
            }
            set {
                this.idTipoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void NuevoCompletedEventHandler(object sender, NuevoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NuevoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NuevoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioEntidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioEntidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DevolverUsuarioCompletedEventHandler(object sender, DevolverUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevolverUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevolverUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioEntidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioEntidades)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591